export { HomeNewsItem } from './NewsItem'
export { HomeSliderItem } from './SliderItem'
export { HomeSocialItem } from './SocialItem'
export { HomeNewsTab } from './HomeNewsTab'
export { HomeStudyHeading } from './HomeStudyHeading'
export { HomeGalleryItem } from './GalleryItem'
