export { HomeSocial } from './Social'
export { HomeNotice } from './Notice'
export { HomePartner } from './Partner'
export { HomeGallery } from './Gallery'
export { HomeTutorial } from './Tutorial'
export { HomeBannerSlider } from './Banner'
